version: '3.8'

services:
  engine:
    image: thirdweb/engine:latest
    ports:
      - "3005:3005"
    environment:
      - ENCRYPTION_PASSWORD=${ENCRYPTION_PASSWORD}
      - THIRDWEB_API_SECRET_KEY=${THIRDWEB_API_SECRET_KEY}
      - ADMIN_WALLET_ADDRESS=${ADMIN_WALLET_ADDRESS}
      - POSTGRES_CONNECTION_URL=postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@postgres:5432/${POSTGRES_DB}?sslmode=disable
      - REDIS_URL=redis://redis:6379/0
      - ENABLE_HTTPS=false
      - LOG_LEVEL=debug
      - CORS_ORIGINS=*
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    cpus: "0.5"

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 