version: '3.8'

services:
  engine:
    image: thirdweb/engine:latest
    ports:
      - "3005:3005"
    environment:
      - ENCRYPTION_PASSWORD=secure-encryption-password-123
      - THIRDWEB_API_SECRET_KEY=T3f58epey_3XwXv9dF1r784NffOpOF1xygc_LaTPsA12rn4aDEpGYz_x6o3Ew9BlruXxHstzZYe8wiiqpRITkA
      - ADMIN_WALLET_ADDRESS=0xD16ECd32Ad107D0b909130b325c79B64cf3C0d28
      - POSTGRES_CONNECTION_URL=postgresql://postgres:postgres@postgres:5432/postgres?sslmode=disable
      - REDIS_URL=redis://redis:6379/0
      - ENABLE_HTTPS=false
      - LOG_LEVEL=debug
      - CORS_ORIGINS=*
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_started
    cpus: "0.5"

  postgres:
    image: postgres:14
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  redis:
    image: redis:7.2.4
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  postgres_data:
  redis_data: 